=== 0xced/Typhoon/schema/schema/assembly.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://jasperblues.github.com/spring-objective-c/schema/assembly" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:assembly="http://jasperblues.github.com/spring-objective-c/schema/assembly">
  <xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="xsi.xsd"/>
  <xs:element name="assembly">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="assembly:component"/>
      </xs:sequence>
      <xs:attribute ref="xsi:schemaLocation" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="component">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="assembly:initializer"/>
        <xs:choice>
          <xs:element ref="assembly:factory-method"/>
          <xs:element maxOccurs="unbounded" ref="assembly:property"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="class" use="required" type="xs:NCName"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="scope" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="initializer">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="assembly:argument">
          <xs:attribute name="selector" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="factory-method">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="assembly:argument">
          <xs:attribute name="selector" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="property">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="value" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="argument">
    <xs:sequence>
      <xs:element ref="assembly:argument"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="argument">
    <xs:complexType>
      <xs:attribute name="parameterName" use="required" type="xs:NCName"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="required-class" type="xs:NCName"/>
      <xs:attribute name="value" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== 0xced/Typhoon/Tests/Resources/SingletonsChainAssembly.xml
<assembly xmlns="http://www.typhoonframework.org/schema/assembly"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.typhoonframework.org/schema/assembly
          http://www.typhoonframework.org/schema/assembly.xsd">

    <component class="SingletonA" key="singletonA" scope="singleton">
        <property name="dependencyOnB" ref="singletonB"/>
    </component>

    <component class="SingletonB" key="singletonB" scope="singleton">
        <property name="dependencyOnC" ref="singletonC"/>
    </component>

	<component class="SingletonC" key="singletonC" scope="singleton">
        <property name="dependencyOnNotSingletonA" ref="notSingletonA"/>
    </component>


    <component class="NotSingletonA" key="notSingletonA" scope="prototype">
        <initializer selector="initWithSingletonB:">
            <argument parameterName="singletonB" ref="singletonB"/>
        </initializer>
    </component>

</assembly>

=== 0xced/Typhoon/Tests/Resources/ExceptionTestAssembly.xml
<assembly xmlns="http://jasperblues.github.com/Typhoon/schema/assembly"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://jasperblues.github.com/Typhoon/schema/assembly
          http://www.appsquick.ly/schema/assembly.xsd">


    <component class="NSURL" key="anotherServiceUrl">
        <initializer selector="URLWithString:">
            <argument parameterName="string" value="http://dev.foobar.com/service/">
                <description>
                    This will fail because the required-class attribute is not set.
                </description>
            </argument>
        </initializer>
    </component>

    <component class="NSString" key="aBlaString">
        <initializer selector="stringWithBlingBlaBla">
            <argument parameterName="specification" value="blue"/>
        </initializer>
    </component>


</assembly>
